### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by JustIngvarr** [SharpBit/brawlstats#17]
**Describe the bug**

pip install brawlstats

```
Collecting brawlstats
  Using cached https://files.pythonhosted.org/packages/bf/09/279c766f71ed6d8696b4b8ce73994560d497ae2b39c5f451452f61c5b88d/brawlstats-2.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/brawlstats.egg-info
    writing pip-egg-info/brawlstats.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/brawlstats.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/brawlstats.egg-info/requires.txt
    writing top-level names to pip-egg-info/brawlstats.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/brawlstats.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/brawlstats.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/brawlstats.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wragy7qc/brawlstats/setup.py", line 48, in <module>
        del data['info']
    KeyError: 'info'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wragy7qc/brawlstats/
```

**Additional context**

Ubuntu 18.04.2
Python 3.6.7
pip 19.0.3
setuptools 40.8.0

What could be the problem?

**Comment by SharpBit** [comment]
Try again now, should be fixed!

**Comment by JustIngvarr** [comment]
Thank. Installation was successful.

**Comment by MinerChAI** [comment]
Have it on Heroku
