### ISSUE TITLE
Heroku can't install

### ISSUE THREAD

**Issue by MinerChAI** [SharpBit/brawlstats#22]
**Describe the bug**
I'm trying to host my bot on Heroku, and it fails to install `brawlstats`

**Full Code**
**requirements.txt**
```
aiohttp==3.4.4
brawlstats==2.3.0
clashroyale==4.0.1
discord-webhook==0.4.1
git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
getgist==0.1.2
lxml==4.2.3
```

**Expected behavior**
`brawlstats` should install successfully

**Actual behavior**
It fails on installing
```
Collecting brawlstats==2.2.2 (from -r /tmp/build_83abd8b4ec208f6826aa36542e36e247/requirements.txt (line 2))
         Downloading https://files.pythonhosted.org/packages/d1/be/19d70b4dc24e8352fec72fd64dd180de80d07d3540a8d91c7a935fc7a5cd/brawlstats-2.2.2.tar.gz (154kB)
           Complete output from command python setup.py egg_info:
           /app/.heroku/python/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
             warnings.warn(msg)
           running egg_info
           creating pip-egg-info/brawlstats.egg-info
           writing pip-egg-info/brawlstats.egg-info/PKG-INFO
           writing dependency_links to pip-egg-info/brawlstats.egg-info/dependency_links.txt
           writing requirements to pip-egg-info/brawlstats.egg-info/requires.txt
           writing top-level names to pip-egg-info/brawlstats.egg-info/top_level.txt
           writing manifest file 'pip-egg-info/brawlstats.egg-info/SOURCES.txt'
           reading manifest file 'pip-egg-info/brawlstats.egg-info/SOURCES.txt'
           reading manifest template 'MANIFEST.in'
           writing manifest file 'pip-egg-info/brawlstats.egg-info/SOURCES.txt'
           Traceback (most recent call last):
             File "<string>", line 1, in <module>
             File "/tmp/pip-build-q1klefls/brawlstats/setup.py", line 48, in <module>
               del data['info']
           KeyError: 'info'
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q1klefls/brawlstats/
```

**Additional context**
Python Version: 3.6.5
brawlstats Version: 2.3.0
OS (and version): I have Windows 7 Pro

**Comment by SharpBit** [comment]
Notice the top of the error: it says collecting brawlstats 2.2.2 even though you specified 2.3.0 in your requirements.txt, seems like something is wrong with heroku/your requirements.txt but I'm not sure

**Comment by MinerChAI** [comment]
I updated it, changed requirements and tried one more time, but forgot to change error text

**Comment by MinerChAI** [comment]
Lol it works now

**Comment by SharpBit** [comment]
For future reference, duplicate of #17
