### ISSUE TITLE
Leaderboard is not currently working

### ISSUE THREAD

**Issue by SharpBit** [SharpBit/brawlstats#4]
```
Traceback (most recent call last):
  File "brawlstars.py", line 20, in <module>
    loop.run_until_complete(main())
  File "C:\Users\SharpBit\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "brawlstars.py", line 17, in main
    lb = await client.get_leaderboard('players', 5)
  File "C:\Users\SharpBit\AppData\Local\Programs\Python\Python37\lib\site-packages\brawlstats\core.py", line 129, in get_leaderboard
    return Leaderboard(response['players'])
  File "C:\Users\SharpBit\AppData\Local\Programs\Python\Python37\lib\site-packages\brawlstats\core.py", line 12, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\SharpBit\AppData\Local\Programs\Python\Python37\lib\site-packages\box.py", line 301, in __init__
    for k, v in args[0]:
ValueError: too many values to unpack (expected 2)
```

**Comment by SharpBit** [comment]
Fixed in [ebc7e90](https://github.com/SharpBit/brawlstats/commit/ebc7e902698a0969e003326aa7e3efed059362e1)
