### ISSUE TITLE
NotFoundError: An incorrect tag has been passed.

### ISSUE THREAD

**Issue by milan252525** [SharpBit/brawlstats#46]
**Describe the bug**
`brawlstats.errors.NotFoundError` being raised while using `get_club()` function of `brawlstats.officialapi.models.Player` object.

**Full Code**
`club = await player.get_club()`
The rest of the code is not needed as it doesn't work wherever used.

**Error**
```
Traceback (most recent call last):
  File "path", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "path", line 178, in profile
    club = await player.get_club()
  File "path.../python3.8/site-packages/brawlstats/officialapi/core.py", line 182, in _aget_model
    data = await self._arequest(url)
  File "path.../python3.8/site-packages/brawlstats/officialapi/core.py", line 140, in _arequest
    data = self._raise_for_status(resp, await resp.text())
  File "path.../python3.8/site-packages/brawlstats/officialapi/core.py", line 110, in _raise_for_status
    raise NotFoundError(code)
brawlstats.errors.NotFoundError: An incorrect tag has been passed.
```

**Additional context**
Python Version: 3.8.1
brawlstats Version: 3.0.3
OS (and version): Ubuntu 16.04

**Comment by SharpBit** [comment]
When did you last update the wrapper? Either revert to 3.0.2 (stable) using `pip install -U brawlstats` or update to what I just changed today `pip install -U git+https://github.com/SharpBit/brawlstats`

**Comment by milan252525** [comment]
I am using official API...
I have already switched to api.get_club(player.club.tag), but thanks for fixing it.
